services:
  planin-be:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - dokploy-network
    environment:
      - PORT=${PORT:-3001}
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - RUN_SEEDS=${RUN_SEEDS:-false}

networks:
  dokploy-network:
    external: true

